version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.flywaydb.flyway
    versions:
    - 7.7.0
    - 7.7.1
    - 7.7.2
    - 7.7.3
    - 7.8.0
    - 7.8.1
  - dependency-name: org.flywaydb:flyway-core
    versions:
    - 7.5.2
    - 7.5.3
    - 7.5.4
    - 7.6.0
    - 7.7.0
    - 7.7.1
    - 7.7.2
    - 7.7.3
    - 7.8.0
    - 7.8.1
  - dependency-name: org.jdbi:jdbi3-core
    versions:
    - 3.18.0
    - 3.18.1
    - 3.19.0
  - dependency-name: org.projectlombok:lombok
    versions:
    - 1.18.18
    - 1.18.20
  - dependency-name: org.scala-lang:scala-library
    versions:
    - 2.13.5
  - dependency-name: org.pitest:pitest-junit5-plugin
    versions:
    - "0.14"
  - dependency-name: info.solidsoft.gradle.pitest:gradle-pitest-plugin
    versions:
    - 1.6.0
  - dependency-name: org.owasp.dependencycheck
    versions:
    - 6.1.0
    - 6.1.1
    - 6.1.2
    - 6.1.3
    - 6.1.4
    - 6.1.5
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.2
    - 2.4.4
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.github.ben-manes.versions
    versions:
    - 0.38.0
  - dependency-name: com.google.guava:guava
    versions:
    - 30.1-jre
    - 30.1.1-jre
  - dependency-name: org.springframework:spring-jdbc
    versions:
    - 5.3.3
    - 5.3.4
    - 5.3.5
  - dependency-name: org.openjdk.jmh:jmh-core
    versions:
    - "1.28"
    - "1.29"
  - dependency-name: org.sonarqube
    versions:
    - 3.1.1
  - dependency-name: com.fasterxml.jackson.core:jackson-core
    versions:
    - 2.12.2
  - dependency-name: net.serenity-bdd:serenity-gradle-plugin
    versions:
    - 2.3.12
    - 2.3.13
    - 2.3.31
  - dependency-name: io.spring.dependency-management
    versions:
    - 1.0.11.RELEASE
  - dependency-name: org.yaml:snakeyaml
    versions:
    - "1.28"
  - dependency-name: uk.gov.hmcts.reform:service-auth-provider-client
    versions:
    - 4.0.0
  - dependency-name: org.mockito:mockito-junit-jupiter
    versions:
    - 3.7.7
    - 3.8.0
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.7
    - 3.8.0
  - dependency-name: org.testcontainers:postgresql
    versions:
    - 1.15.1
    - 1.15.2
  - dependency-name: org.assertj:assertj-core
    versions:
    - 3.19.0
  - dependency-name: org.junit.jupiter:junit-jupiter
    versions:
    - 5.7.1
  - dependency-name: org.hibernate.validator:hibernate-validator
    versions:
    - 7.0.0.Final
    - 7.0.1.Final
  - dependency-name: io.rest-assured:rest-assured
    versions:
    - 4.3.3
  - dependency-name: org.openjdk.jmh:jmh-generator-annprocess
    versions:
    - "1.27"
