sudo: required
language: java
jdk:
- oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:
- cd am-lib && ./gradlew build
deploy:
- provider: script
  script: "./gradlew bintrayUpload"
  skip_cleanup: true
  on:
    all_branches: true
    repo: hmcts/am-lib
env:
  global:
  - secure: ZNaNkz7369onteUmPQeoGsILFGXhD2/PJBfPJmKQKAGYqPmhfBYEUFGjsukLi02URvwviIenntzJ5y4TE5a1oUKc1AEyWAq79iVqjkxjLP2sY9ZLNkuTRYptrqUXx5ElJPvb19jrjJcMvMwikmXa1vPOGAGNBZnr/QY0EIwAPdFDdsMKGg9IuT5vZcmBLufJV9QXAcoogRxL7ZS9inL7F4sfHVGBk4cL7gMDLd+/mq89rWLNAxJdfkFc83z/NzW7fc6c/hSeuHnIRnaCFFYaodUTOFObnCJVuyzafCcJ72/FOc8XkNnoM/69PUlgGDu65UNXcve9qg4n2ks52D/o+N6zkhKLqvg81TlQh9liQjVEgICPYbVj+WFzSyVLYvO3+VtK0pQE/HpMXypm23cIXKMmgooHj7Luj9R75HCtk82vUrQVWv0Djdjm1afA3BL22b4Q+hN0Qu3GYhZc2zCfsf1/87+TMoJFtEBGzzcUWuK/fTnH4rW5KeiBRG18fQyxFaHOYbygz3S2l+bF5dwGP2f8/Agvyemx2A2lNOQQ0zAOVBNRXsLF2LTlPCprbjY2dAyHYGOFXZHieLtpeMLYfmNJr3q63DlN/UtO0Lo2pXsYzEMTeNcULaUlrO7qJ2mcq/aoT2MRjAy5N8GMPqO8Q5u/NwbM/E2WkfmbzysbVis=
  - secure: WqWj/qYO/DMeWjQlpa4QXhntC4y4KniNJACt5PrzcGkqdxno6GoGuJnAznXlbUTSI73yRbO9jzRPjCX1JZzvqKTGswhmsBbR1Sd3rbNncYAd1MarUM71011XSUln+6lzQfj+2V8orEoej3Qt88YeKk1geL+WzJqzCXVf1y6khAZmtwGW/xa/wKYc9BYqWYqgNY/HVgoyStrafET1qv8pv8sCeATsw0C+6gkLhM8gc+E+9r1RCxhQyHAnsu9dfY0p2JpUQ5CFUadxzWRng6zqQnLrxqYNYnAG9Fl36oUfYr74WLReho9orMYxxmBc/YTvDaS+pDAcwtCgBgdmXK9LRXt8449qlb8p9plXYK7Yaca3BIMxnxsCltOx8LVyiNFpej20OTPYZ2rHa4JNPDr672WOlDWLoSivVnISEBIm17bGxoy6pVe5zwimoYbZRH/UPKMNw359tOSEtDZENribnDFGFgHGBFfRTp2IwA7+tVHcnAtfDzapC7zQjbRY41I4B3ETD4K4d3+qU8/j0yeeyl/mN9cMe4+H4dPRuB2rAWGZCrsiVvTyuINDkC8++SO2AIKtUJUA49ku66V7q4YQ4dINAoHWMArjHGqBZ2rFWa2Ds3FiCjZ0tNRSiQdctSOwfxOYhorn+deE8BPTXOHQUtPYyTIqOgXEj28sIlImciY=
  - secure: VLaogjX8Mx0WbDbvyf7QoeeknNpMKdC86OOhHmDibK3BOKohuy6cf79u/zz4x2jcwoULUxEra91dXQWk1F+CcQhp8WcdLY+0ieVjhKPpaAPg6Mlw6XJ2jJkBL/BgnTXL0duu4gMV+mVayrFWRkjbDAKiz2YGElYTlt4ymb89czf8un2IMB/M3+a1R4I0d3/64G83yoq9hxRcgltZTS2rqwJSUQBKOACY+l46/vt1SWd7cO7qSSK2pwpbpEJ9Kaopzc1OQppm7qtZkYPSA7leMnQ9nhlLuluxxy2u+IRy9DSItsq8IwUK2tTdSc63DCY3SJcpqQOQQ8L+JHZyd01JsDW0ariZQ6eP4j+eMNVzZbfup6zNROu6FPX4iGT4i8jx1Osanafv0SLKnWm7J2wF0xs1wH2KNDd7/iBcZFf9HfK6/yPXjaXEykMw+FEVkqNacgV2xc0pp4gleGjy9TLwaWJ+XqkoH9+rpgkuLzFgqFAOShh3awUDj9IjwnpzoX5ydmzvLJCuO55RG7JeO1ZOfKgRsf6xkB8eg+xYcEq2TsNBK6Q0Dcpr2ThGFB+UdXkyNJktLRLy8h8T37JYXYSwCpqcKgLLpMntaQDWFAag4gduvwRmz2yO+SArOKu5RBTksqUYpFNoUSJqlaa+ORUfLiGIfPKtdGIx56ACUH4+07g=
  - secure: jTF4B5xqoopFN5ixsIOPMCvqPEn43H+nd71iIg3BK4GT4bPjd+DLF+XbpLTyA6FK2eLe8Zh803Y5E6ahIJ6V5aqqMXtw4p3rPXiUXYC9xW4XWSn7pEHu3TqMvj4kD4OGIyJU9o9mOOnsZlQAoMdpryl+aXUPx69Wf5+/wpwEBsZMR+a8AzmP3VYILkhoTc6mY+QZJTyJsSmUbjs3mo+SV4+ZRvxVhu3lNDYYp2TGLpYOcgeU6TuRL6ywe4j0YZ24YezKsKKancYmTVoSOO9r1a21x7u9BH0iplJUwMBSlK5EByI/oPuYZcRTE/HQqzfo/coBIEWLBzsaOUlq3oM0CoVh8LSinkcY4iQFkbXdzmFdTyRMLgtW9f02qffk6PMc3CmBlVLNC/bijWMYk7f9anyt23gVTllQBb1HJuRrVSirZ+jItxcnFZAbLssVlIAYYk9vwOshozmhXDMFDt1ug3NSWUCrhvmyOns+VPvJRTEEwDKBTrEnAZ77+OItQWM2eTySK4uB5nQflnQcZhKfKRYubK5HK8dpwLNGpG5gX+GBQR31mN2PiwPEBMtq9cb+Iuguzt+EjfWgoYPNHd/ySeg5ZaGvpIj3qYxBn2sqI0LUPUwChufaYjzui44bq/hSFoeCh4QhvnJ89RizZQMsHb4i+moPgg9KEHJLLHVbR60=
