sudo: required
language: java
jdk:
- oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:
- cd am-lib && ./gradlew build
deploy:
- provider: script
  script: "./gradlew bintrayUpload"
  skip_cleanup: true
  on:
    tags: true
    repo: hmcts/am-lib
- provider: releases
  skip_cleanup: true
  file_glob: true
  api_key:
    secure: ZlXQNag/UCBep49GttAOd+4ceEKcXoCwtvhiataxcUEGgdDaof8GgKHvGCwXuhr+tdXQDTSZCV10WaEQOBfiexpdURjwd1RFqnJsfFDqFGOjiE8IOR+Iamt/TRUyX4xKbUsxQN9+HHxZ7zvkVrBVQMUI1xQhW2OuurPge8Y/3wTcSyA4khZc8RtTfakwZszjjdneDXOaLaG9YkDO3gWLmL1FzrLJRIVEsRObScVO9n0CXfSlSEjtbgIzbJ5S6+6iXTWpjok3o2gITWri8GocX4HGxTOM7di4pLrGx12eK0XTxK5YTIuUKnh3wZdMI/u/f5cNVP2K6R9VVYYM4/bzxdL8nccsmsWREGcvPLjNS6V7aEfHexGjZKR1hP8McaUeZRmnBEklgAH4qIcatmuXPe6rndf4LyMnQdHqVUzxS0LkhwrwTqKcTW5Lv/rrTBStEZjDWuZtposRuBpX5zeiAhrMto4vqf2td+VY9p1cJOc8ufw4/fkBk27lBu0HLebTMwYWOdcqVlHJLNTPnX9p6yjmuMN1eQl6/KiKvDgNUlA1ghicxDp2qhu373h0dPbYOatmyJ8eFu22z4vDEQPvusuQKEwSeymEjwL2xtUzJY9VLETOLN4wiBze/7dL67MB1b2FEEv1O9zIiC9TKxUCiMc95TDAd0b5ZuFrEqtdtMM=
  file: build/libs/am-lib-*-all.jar
  on:
    repo: hmcts/am-lib
env:
  global:
  - secure: UcgFzysCDjcJMJUZnB9GO9IYodiuvCcF2G04oLJbA0jN/gC5TZI36fvbkTqOvzwzh3oEahsVIIYVdsCxN+243CWy65kmfPahKe13/U6zJi0X0LArmcOX368VHRQ92nCBHaFzQhTPnXDNYre8B955CU8RvAcKI2Zu0960X+mcvAVjHhuB4mrtseGcJUMwAwiJx7s1QK59NJK+z3olWMCmlRBzVKYmwhE0XHB/WU20m570G8+J74GBCC6CwSE9EPJwrG5ybHPjhUQaz/HH2RzXXabPbM5XUzd82oBsidvU9pbxgSfvwgAZXgOP7LG5goPhww7efICGNGQ6iGSH/umzeW0lELBsMfeaOkuurrv/LcMassqxcUVOf4Ub/6XB8HVlZKS7KMvvC5g4/eXvl4e+s5OLX+/jUEKmzpCYsgTM9q0Fpso094by2aO8YcytsHhZGnqXO3mham0n/5jZdlooSaFt+Jgdd71TfiVSeh/dPjuewxpV+vRJv2C3uhmLauTzKcFwrc78ZG8F3td0yTNhZT67rGo+9SO3qTxwAMtYkWaWArbi6uKyHsDD0LJewkJADo2mGSmsg+N8k0ZWj/3E3t5/PRbzf8ReS3d4eXLSCXoJuBHUl9lBKeUK+uBzhqc5zeU4vsG1QqQ07hGpJ4KNn31zpRy6MUfRBQCRDPwPIsI=
  - secure: mrYOAC00pAaJH7eUAtssxmaH15gU/IOYYsL+GY2nmEQBgIk4d916dzroUm6rib8bWwbDQbYOhwhzJPn9An/VUY6lPXFLo5Q5vkuGci4j3aGP/TPE41KhqPtrPRgPHyaCjP6AZ8ivKJezpGhvAkTdxWk6g2FDzH2El+RukVYkAzVi40QFOHjCf7jE8NHLeu+jcvGS3yCFM4LjwcQ4VpD7f6AIaklWRFsCA1973dnMLl7CZXrBY2yowxXIKQu8YLkcG4by0ljl2SSx/njrnYMVRIwjWv8m/r9MOTot3UnO87Ly/Uh466bvaMOB7oqbvf6yt15fiGRoLjon7PV0lenUb7EPWGyzZNKkSTmQYXTGy5WMo8azYDSQgvdNFoe6Vh38wF1z8r4/w+C/lUYOEuc74UTBU7ho0hmKS66rAu+Qxp3l1vkfCWvSIJKDsnfoWqU7/hZ4N8Aq7s1vrQAf1I+quZDvHqNWQ97tnkscTFirG+eC09UdRHRJBR8Qd6UO9H5RjNG6jsU0F4T/w87PmRjeiQEA6oeimdy1aM1vo38ArS3SIAKnJGX0KE3Q7iriyRSymcLxUL3Iiaq4dljYKQeQOpnWS2OXHPL1rG9RGevYAnA4mCv50nLhgjGMChjQJFIiMFa7a3Ja5cuolpiuugSS3QaKM9VvJAMjS7xxpQq8v+k=
