sudo: required
language: java
jdk:
- oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:
- cd am-lib && ./gradlew build
deploy:
#- provider: script
#  script: "./gradlew bintrayUpload"
#  skip_cleanup: true
#  dry_run: true
#  on:
#    tags: true
#    repo: hmcts/am-lib
- provider: releases
  skip_cleanup: true
  file_glob: true
  api_key:
    secure: YNNf3uSvh+hZ1oz/HtLCiabD8H01VKm5JI5nYmbUNgrZI/PrFTKfGYjIfx3GbXv/sbxb+y3nyR1dybq7iaEGXV1Vfso80BGokyAsL/qHvnhG6tpc9SgU6BgupjrK5s355x07eKdBVY7gf7k5vYEtJjB2X7CNZ051NHjeoMInfysSkVrUr5YjbJFJQehCKXxwzDY742SH85j6kYP48YeVlEnhQYBvh1zvG5WhXmMn3GliJ9vWcRiSNviD3MMADpUfavR4qrOCwVrwPXDYQpRfeK4fKYawQc0Kha72+cmLOmqF29D0bie+xui+XEV6g79JZZxgO130NZzQVZzhk/ZqKAH1G0ZkcSMDbnCRSpFfjPzzsLjKWm0pq/U78Syv2Uz24t1ea8dWSulePGu/zECri2Utn2tJRgyAFBS8QUn3BhShJ3G80AkAyCzjCfTu625BGMo3QAmjhfgHlaJNfN5J8hX9ILP2rq/ClOPem5+4X1puc14gcii/GraveC4p0t2qCvqHEG+PtFqbo3lgAAiEKdK2tcB5FSPmSs/aa8r9zXvMLwihmYtt1zk3Cztq0GXVyX+uLiWdxjZMjFncHgUhWHepccCytUS0GGDnsbyWjAmbwMEss96m218rFV1m3yMrgj7/QceHDPPB1g4BVk32/YtwRejNPlHn2tpHwSDb0lM=
  file: build/libs/am-lib-*.jar
  draft: true
  on:
#    tags: true
    branch: test-travis
    repo: hmcts/am-lib
env:
  global:
  - secure: UcgFzysCDjcJMJUZnB9GO9IYodiuvCcF2G04oLJbA0jN/gC5TZI36fvbkTqOvzwzh3oEahsVIIYVdsCxN+243CWy65kmfPahKe13/U6zJi0X0LArmcOX368VHRQ92nCBHaFzQhTPnXDNYre8B955CU8RvAcKI2Zu0960X+mcvAVjHhuB4mrtseGcJUMwAwiJx7s1QK59NJK+z3olWMCmlRBzVKYmwhE0XHB/WU20m570G8+J74GBCC6CwSE9EPJwrG5ybHPjhUQaz/HH2RzXXabPbM5XUzd82oBsidvU9pbxgSfvwgAZXgOP7LG5goPhww7efICGNGQ6iGSH/umzeW0lELBsMfeaOkuurrv/LcMassqxcUVOf4Ub/6XB8HVlZKS7KMvvC5g4/eXvl4e+s5OLX+/jUEKmzpCYsgTM9q0Fpso094by2aO8YcytsHhZGnqXO3mham0n/5jZdlooSaFt+Jgdd71TfiVSeh/dPjuewxpV+vRJv2C3uhmLauTzKcFwrc78ZG8F3td0yTNhZT67rGo+9SO3qTxwAMtYkWaWArbi6uKyHsDD0LJewkJADo2mGSmsg+N8k0ZWj/3E3t5/PRbzf8ReS3d4eXLSCXoJuBHUl9lBKeUK+uBzhqc5zeU4vsG1QqQ07hGpJ4KNn31zpRy6MUfRBQCRDPwPIsI=
  - secure: mrYOAC00pAaJH7eUAtssxmaH15gU/IOYYsL+GY2nmEQBgIk4d916dzroUm6rib8bWwbDQbYOhwhzJPn9An/VUY6lPXFLo5Q5vkuGci4j3aGP/TPE41KhqPtrPRgPHyaCjP6AZ8ivKJezpGhvAkTdxWk6g2FDzH2El+RukVYkAzVi40QFOHjCf7jE8NHLeu+jcvGS3yCFM4LjwcQ4VpD7f6AIaklWRFsCA1973dnMLl7CZXrBY2yowxXIKQu8YLkcG4by0ljl2SSx/njrnYMVRIwjWv8m/r9MOTot3UnO87Ly/Uh466bvaMOB7oqbvf6yt15fiGRoLjon7PV0lenUb7EPWGyzZNKkSTmQYXTGy5WMo8azYDSQgvdNFoe6Vh38wF1z8r4/w+C/lUYOEuc74UTBU7ho0hmKS66rAu+Qxp3l1vkfCWvSIJKDsnfoWqU7/hZ4N8Aq7s1vrQAf1I+quZDvHqNWQ97tnkscTFirG+eC09UdRHRJBR8Qd6UO9H5RjNG6jsU0F4T/w87PmRjeiQEA6oeimdy1aM1vo38ArS3SIAKnJGX0KE3Q7iriyRSymcLxUL3Iiaq4dljYKQeQOpnWS2OXHPL1rG9RGevYAnA4mCv50nLhgjGMChjQJFIiMFa7a3Ja5cuolpiuugSS3QaKM9VvJAMjS7xxpQq8v+k=
