sudo: required
language: java
jdk:
- oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
script:
- cd am-lib && ./gradlew build
#after_success:
#- ./am-lib/gradlew codeCoverageReport
#- bash <(curl -s https://codecov.io/bash)
deploy:
- provider: script
  script: cd am-lib && ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    all_branches: true
    repo: hmcts/am-lib
    #tags: true
- provider: releases
  api_key:
    secure: f90s/M0JeoOwZENfReNfEg3Y4ThaDfVS9o/D3lCqQZYvzdqbkWVWpwT9y1dnYPT0yARujoJTy8qrOmoStr8Sz2PuWgWVHfRhIIcn858dxz9Auprs8cFaSqlZS2ynIy33EsasSaFmCb95X1mMaifiNi3GHwJDdpCc9AOXV2EGEhkbgug5MaEgkxg1n22v3F4ciTIdWrl258HUVCoVVOs64tEQ69B1n0TRBP18mRJNnY+bsXkYJ9/Jb+Mc9xz2NhmHFZ+K9IC5z2ds1PTRgzLOV3fviyplflWxME6yK+FDKilhDqAbwzaVpLYE8n4SfMgBkrx1M9Y4ZpCHj+x4mJ9jTGwHhYta+un9H5LYyxZGewfcJ0oOqGR8kOvVtrnPYkCgfMT9vA0gNSezVg60kcnLtZ2YYe/H5xlJbg1GmLwOxq0Gpa196E2IYGvMNEfOHkiShhme2FQ3iptYnzDqvccXVZ4/PHoIM7Y1z/FsRJXMjmFZAwUFLgxhanylrPcoWd/N98VubZKvm5leOrpyPhqGiczKMTBuBWXtNaEoW25cj85P7D+zZ9jcFkMoOgGQv/wZ8zKeK5/BS0on2526dN085fMbvbmZJoKktxNJaj/dsRdLOtzQ8drqz0jAmPVt8ErWL4pYBUBNCjSf1N40EMykJpt26vyvEwN05Q+LFU37XjM=
  file_glob: true
  file:
  - /am-lib/build/libs/am-lib-*.jar
  skip_cleanup: true
  on:
    all_branches: true
    repo: hmcts/am-lib
    tags: true
env:
  global:
  - secure: idyabL0MgrmQw8ZdwgRYe8/ewYrdYlNAaYUZbhTzLnnIkXAnPXhFxPB+k2mDaMf0ww26VpBl4O6aYv5bHrCI+1/oziByTSz6Qny9j3F2h/gnSwyXZUe427BCjTR9Wz1+TvASGansO+igj0FxENGikqKDd0V5Qe8lr4Lm01+xXLoAXfvyqqiAqjsRHvl1vG+9F+G80hzmMBSBm7AkN//uYJRFCJV07yp6J0ALd6Z81cChNJgvS7oG9iXimFltiCwf8KNcotkm/mbGHULyj6YVfnFePSoIuI94QBi2myqxDRQ56bv7wtipsF0zaOn+Zc5hPr6QGPMXNWeD3kp/ZmEYWsg5VFQEdcpnKhyv7zcmKZDaYQgIkdjZTZ1rDBj04ubBJs96dEex2CamascLTuq5XuVs3O8MG4GrcKPDqTbDNDnSVDtyRUakhWwnFn424shotCyXl+k06THlFVQq229eBRKCQDdGWtV2B4Z55AxQdIHqaDLppYJs1wCC7350/gY0pXgm4928UpVxx3Bk/Gu1HT8gIWOiEYigqqPOgFlfrdGMiPyRM0WHImZ9Ru8d/RvMnGYndwlY10q3i2lM+CdwthaPp1f9jZDZw2uqqmiUlOuH+oVG4l61h+gznlH277KXcjTPbLjwczo5nZ0L4H/TBGTVrhTOVUQEsBu/zYrAZo8=
  - secure: lMbaGTv2PCsjiwGpDMsTKShmtC6Fj6bp++2Re2H2+lgRAmepnr9h8+5ckHyaGYH6HuxSBYN9Q01F1t6lwn1tZQYhJ6EJYK8Kb1KHWnXME3K6VnM/C+6Yr7TkZr0+1SaDE7CIAjCzgF3v5MsWlBUDLhJYViwNuZaJ+Ej73RJkIi0qEu2Dk0PYx6JMK/jwnCojCOYoWjm7d23Tyu5ACo+onZF1WCfVVrI7Gq8kEN4OhClozVvF5IFqfeGEJCWzMsNCxJDE9ptFJcDmp5he41l1GrXNgD9rCxWay03l96Z2+OcqeXV9prIZ36h1mnWy3pd+Xnpxi0LqE09nBFnnGMCwbeer16hG09zsxav6Qk68AUt+smHEcxzFJC9Q6otW+6ud8gxk4kxPkyYo0+adQj5yuudVNS8R7sH8hsTKdD6K0Hv5I3Yob2eSw+1aaE1iz8vplbMCdwOVuZH9uwpgWrivi4HZO9VKgkZ83nr7guJpES7i+YhmiokpN8eUZFrUKCW0ScUJGit8JBjOeaSZod6prd/X7roI4u79eeYG0l76PcN/vPgfUN4cQEOOwg97XLpAvYySghC5ppRUnczDs/iEV5sqWS2QnF20JY+2CDEJkrfC/JlpR2TETrVzeBfzs/VKm811vAoRXscaGWGCfg2FdAWHvpquQ8EViqKnzH/9V5M=
