sudo: required
language: java
jdk:
- oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
script:
- cd am-lib && ./gradlew build
#after_success:
#- ./am-lib/gradlew codeCoverageReport
#- bash <(curl -s https://codecov.io/bash)
deploy:
- provider: script
  script: cd am-lib && ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    all_branches: true
    repo: hmcts/am-lib
#    tags: true
#- provider: releases
#  api_key:
#    secure: f90s/M0JeoOwZENfReNfEg3Y4ThaDfVS9o/D3lCqQZYvzdqbkWVWpwT9y1dnYPT0yARujoJTy8qrOmoStr8Sz2PuWgWVHfRhIIcn858dxz9Auprs8cFaSqlZS2ynIy33EsasSaFmCb95X1mMaifiNi3GHwJDdpCc9AOXV2EGEhkbgug5MaEgkxg1n22v3F4ciTIdWrl258HUVCoVVOs64tEQ69B1n0TRBP18mRJNnY+bsXkYJ9/Jb+Mc9xz2NhmHFZ+K9IC5z2ds1PTRgzLOV3fviyplflWxME6yK+FDKilhDqAbwzaVpLYE8n4SfMgBkrx1M9Y4ZpCHj+x4mJ9jTGwHhYta+un9H5LYyxZGewfcJ0oOqGR8kOvVtrnPYkCgfMT9vA0gNSezVg60kcnLtZ2YYe/H5xlJbg1GmLwOxq0Gpa196E2IYGvMNEfOHkiShhme2FQ3iptYnzDqvccXVZ4/PHoIM7Y1z/FsRJXMjmFZAwUFLgxhanylrPcoWd/N98VubZKvm5leOrpyPhqGiczKMTBuBWXtNaEoW25cj85P7D+zZ9jcFkMoOgGQv/wZ8zKeK5/BS0on2526dN085fMbvbmZJoKktxNJaj/dsRdLOtzQ8drqz0jAmPVt8ErWL4pYBUBNCjSf1N40EMykJpt26vyvEwN05Q+LFU37XjM=
#  file_glob: true
#  file:
#  - /am-lib/build/libs/am-lib-*.jar
#  skip_cleanup: true
#  on:
#    all_branches: true
#    repo: hmcts/am-lib
#    tags: true
env:
  global:
  - secure: jiC/tPWHu8fF4R9dph1GaYqtZqzNyl/BJD61VbHv//LvHEVKyamTBfs/tMUX1SNWqd37XtF832xVBVCf3birALSeTYKiP3W5n4izvI7d1hqwkixbHnHOBnUvilP/8UCoOOX3JI3AM3PPjgQYRYoFIKgzWQzy0aU2pBKxGO+fqzKD6L6Ni3j6ZqIHrM/IQeuAzjYlD11i1D+dS+SdaNmQ2hg9WkvvVaqtB6+SBWbC5xq3hum8mLZvz2G19WGA9ZMjkG1juuPgTA3ee83zKDmaXkE75NPZ9U0RE0IM4LDcW9i/vn0QvvZZ4LDGwnoDhzfIHiQnnCTZ86AZ715LtGqroXnk+giualqg/lFwqBY8xc7F//KCi06VWANhTbnVkNMLJNxZKy0xxqUhn0r/QnnODVbmaRJ4XuVN2EKSNxv/cXEvC+CSQops8AQhCCZLS8iJniDkQwsCN//8V69EvycGi+lE9qiHTu1g7KHiBv/Zl/HtLBuu6bdKryEPO37YKKX0IajsASw/xG4Q84zNKiFCN+eY6Wuh2xKkaM8vO19VWZEafiY2HAPjKADwbswlcFYhwoy5Ooz47L4yOQKcYB344wY/4Rfh4BPHPg5afFepOSj3Gg8C399w28mZzORLd4j04bwXGgsxBPCndtlq/tG6t8Lc2MGGmXB50Ad7OE6rnpA=
  - secure: iEFmM7YeH9Wfh5r0+15/IICsUBmrEc5jqONlX/AJSJZlXtQGnwZlcAZ3TopNBT9shAOncnRGIYwykGE0WKcX/gfbbZAR7YTofCUpulvcyyptDczeFIPWnPxQKjB0dAoHujiOojgWVUIZs9x+rtFjwsW57DAJPOEqOtQ9WN6yNVoDWc6o/shcScUBK+C6pfBUvZSPN7J1eMaakEAX/8g4bCKSRHqKXlYVhJyN+Sz7ol42V3x8smb0ONGKVOFAQSysTR2upp3Yjewxst0RE1FNk43sxddAG4Gmw/6UvEaXnuL5wUtoRvZusYLTbh5is0eeGZv/dWHQWgHEpGEl6qVywMZGTyXAtbf05oqpOs0mOccIqWCCtiymWgfD7T1J1Nufr+VJeYdcHffI46MIglGqFf6PVDEseJubSabeDuGan6HARacoNsjep3tPJE8lpSqhEh3uqadrjJdQl0QdQNs8kDIoJym4m2LlszlKIcLtCmTMDe352jMG9ByWhZVrQWcHNQxKdcB1uG6ujXnRB6a4ooHC0MFOM+IkX+rauk87WG264IuZL4QSYrnGNtUIzZ6JdZLUxtI8CrrZByS2LgJtcZCjsXvNgi6y/dewOIT4JSFgJaKdPBucWnXYk7goGa3//2YcHXCeSr7Bqf1WsK13JWVegmj3ltE5Xj6sLXZLjCg=
