version: '2.1'

services:
  am-lib-testing-service-db:
    container_name: am-lib-testing-service-db
    build: ./docker/am-lib-testing-service-db
    image: hmcts/am-lib-testing-service-db
    tmpfs:
      - /var/lib/postgresql/data
    networks:
      - am-lib-testing-service-network
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=amuser
      - POSTGRES_PASSWORD=ampass
      - POSTGRES_DB=am
  am-lib-testing-service:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmcts/am-lib-testing-service
    container_name: am-lib-testing-service
    depends_on:
      - am-lib-testing-service-db
      - service-auth-provider-api
    environment:
      # these environment variables are used by java-logging library
      - ROOT_APPENDER
      - JSON_CONSOLE_PRETTY_PRINT
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_TYPE
      - REFORM_SERVICE_NAME
      - REFORM_TEAM
      - REFORM_ENVIRONMENT
      - LOGBACK_DATE_FORMAT
      - LOGBACK_REQUIRE_THREAD
      - LOGBACK_REQUIRE_ALERT_LEVEL=false
      - LOGBACK_REQUIRE_ERROR_CODE=false
      - AM_DB_HOST=am-lib-testing-service-db
      - AM_DB_PORT=5432
      - AM_DB_NAME=am
      - AM_DB_USERNAME=amuser
      - AM_DB_PASSWORD=ampass
      - ENABLE_DB_MIGRATE_IN_SERVICE=true
      - S2S_URL=http://service-auth-provider-api:8080
      - S2S_SECRET=${S2S_SECRET}
      - APPINSIGHTS_INSTRUMENTATIONKEY=false
    ports:
      - 3704:3703
      - ${SERVER_PORT:-8090}:${SERVER_PORT:-8090}
    networks:
      - am-lib-testing-service-network
  service-auth-provider-api:
    image: hmcts/service-auth-provider-app
    container_name: service-auth-provider-api
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - 8502:8080
    environment:
      JAVA_OPTS: -Xmx384m
      SERVER_PORT: 8080
      MICROSERVICEKEYS_AM_ACCESSMGMT_API: "${S2S_SECRET}"
      TESTING_SUPPORT_ENABLED: "true"
    networks:
      - am-lib-testing-service-network
  service-token-provider:
    image: hmcts/service-token-provider
    container_name: service-token-provider
    environment:
      - S2S_URL=http://service-auth-provider-api:8080
      - S2S_MICROSERVICE=am_accessmgmt_api
      - S2S_SECRET=${S2S_SECRET}
      - APPINSIGHTS_INSTRUMENTATIONKEY=false
    ports:
      - 8089:${SERVER_PORT:-8090}
    depends_on:
      - service-auth-provider-api
    networks:
      - am-lib-testing-service-network
networks:
  am-lib-testing-service-network:
    driver: bridge
