server:
  port: 3703

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /

auth.provider.service.client.baseUrl: ${S2S_URL:http://127.0.0.1:8502}
idam:
  s2s-auth:
    totp_secret: ${S2S_SECRET:AAAAAAAAAAAAAAAC}
    microservice: am_accessmgmt_api
    url: ${S2S_URL:http://127.0.0.1:8502}

spring:
  application:
    name: Access Management
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${AM_DB_HOST:localhost}:${AM_DB_PORT:5433}/${AM_DB_NAME:am}${AM_DB_PARAMS:}
    username: ${AM_DB_USERNAME:amuser}
    password: ${AM_DB_PASSWORD:ampass}
    properties:
      charSet: UTF-8
  flyway.locations: filesystem:am-lib/src/main/resources/db/migration,filesystem:am-lib/src/main/resources/db/migrationAks
  flyway.enabled: ${ENABLE_DB_MIGRATE_IN_SERVICE:true}
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
security:
  authorisedServices:
    - am_accessmgmt_api
