ALTER TABLE access_management
  ADD COLUMN last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE access_management
  ADD COLUMN calling_service_name VARCHAR(100);

ALTER TABLE services
  ADD COLUMN last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE resources
  ADD COLUMN last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE roles
  ADD COLUMN last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

