CREATE TYPE ACCESSMANAGEMENTTYPE AS enum ('ROLE_BASED', 'EXPLICIT');
CREATE TYPE ROLETYPE AS enum ('IDAM', 'RESOURCE');

ALTER TABLE roles
  ADD COLUMN access_management_type ACCESSMANAGEMENTTYPE NOT NULL;

ALTER TABLE roles
  ALTER COLUMN role_type TYPE ROLETYPE USING role_type::ROLETYPE
