java:
  applicationPort: 3703
  aadIdentityName: am
  keyVaults:
    am:
      resourceGroup: am-shared-infrastructure
      secrets:
        - s2s-secret
        - accessmgmt-api-POSTGRES-PASS
  environment:
    AM_DB_HOST: "am-accessmgmt-api-{{ .Values.global.environment }}.postgres.database.azure.com"
    AM_DB_NAME: "am"
    AM_DB_PORT: "5432"
    AM_DB_USERNAME: "amuser@am-accessmgmt-api-{{ .Values.global.environment }}"
    ENABLE_DB_MIGRATE_IN_SERVICE: true
    S2S_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
  image: "https://hmcts.azurecr.io/hmcts/am-accessmgmt-api:latest"
